apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-python-public
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-python-public
    app.kubernetes.io/part-of: e2e-python-personal
  name: component-python-public
  namespace: e2e-demo-qawq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-python-public
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-python-public
    spec:
      containers:
      - image: quay.io/codewindbtle/test-images:9d912071c9bf4cdf94592141a973c1be
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
